### ISSUE TITLE
socket.timeout: timed out

### ISSUE THREAD

**Issue by ishaanamahajan** [semuconsulting/PyGPSClient#51]
Hi,
Every time I connect to a NTRIP server through the NTRIP Client Configuration, I get something called 'socket.timeout: timed out.' Is this expected? Or is something going wrong?

Really appreciate any help!

**Comment by semuadmin** [comment]
Hi @ishaanamahajan 

Sorry you're having difficulties, but I'm going to need a little more information here if I'm to help you!

I need to know:

1. What platform operating system are you using? Windows? Linux? MacOS?
1. What version of PyGPSClient are you using? The latest version is  1.3.19 so if you're not already using that version, I recommend you upgrade.
1. Obvious question, but does your workstation have internet access? Are there any firewall rules that might be blocking incoming data on port 2101?
1. Which model of GNSS receiver are you using e.g. ZED-F9P?
1. Which NTRIP caster URL and mountpoint are you using?
1. Is this an authenticated service and, if so, are you providing the correct login credentials?
1. Does the mountpoint you're using require NMEA GGA osition sentences before sending RTCM data? If so, do you have this option enabled on the NTRIP configuration panel?
1. Where are you seeing the error message - on the panel itself or at the terminal?

It would be helpful if you could provide a screen shot of the PyGPSClient NTRIP client panel showing the settings you're using e.g. something like this...

<img width="520" alt="Screenshot 2023-03-23 at 07 48 05" src="https://user-images.githubusercontent.com/28569967/227137194-9fb71ad5-da27-447c-8961-b3bfe6264c2a.png">

**Comment by ishaanamahajan** [comment]
1. Linux 
2. Was using 1.3.17, upgraded to 1.3.19, same result. 
3. Yes it has internet, and port 2101 is working fine. 
4. ZED-F9P
5.  <img width="669" alt="Screenshot 2023-03-24 at 2 42 45 AM" src="https://user-images.githubusercontent.com/73236968/227456854-3ef95e27-eac9-459f-8bac-d5b3a8309df5.png">
6. Yes, because the credentials work on U-Center. 
7. I am not sure of that. But if yes, how can I do that?
8. In the terminal

**Comment by semuadmin** [comment]
Hi @ishaanamahajan 

I did a quick test and was able to retrieve the sourcetable from that caster, and it also returns the expected error message if I try to login with invalid credentials. 

<img width="522" alt="Screenshot 2023-03-24 at 08 28 48" src="https://user-images.githubusercontent.com/28569967/227465684-3c8e936b-9bc5-429c-afb2-22da6109af99.png">

But I can't test the actual NTRIP feed without valid credentials for that caster. Would you be willing to share your password temporarily to help me test the connection (you can email me directly rather than post it here)? If not, I'll need to register with that particular service, which may take some time.

**Comment by semuadmin** [comment]
Hi @ishaanamahajan 

Could I ask you once again to send me a log or screenshot of the the _full traceback_ of the `socket-timeout](socket.timeout: timed out.` error message. Thanks

**Comment by ishaanamahajan** [comment]
Unfortunately, I am having a few hardware issues that don't let me reproduce the error for now. I will close the issue for now, since its going to take some time for me to get back to Pygpsclient to start working with RTK again.
